//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baomatthudientu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Context { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public System.DateTime Time { get; set; }
        public string Status { get; set; }
        public int Delete { get; set; }
    }
}
